/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        // Shadcn/ui compatible colors using CSS variables
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        
        // Primary Colors (Fintech-inspired)
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        'primary-blue': {
          50: "hsl(var(--primary-blue-50))",
          100: "hsl(var(--primary-blue-100))",
          200: "hsl(var(--primary-blue-200))",
          300: "hsl(var(--primary-blue-300))",
          400: "hsl(var(--primary-blue-400))",
          500: "hsl(var(--primary-blue-500))",
          600: "hsl(var(--primary-blue-600))",
          700: "hsl(var(--primary-blue-700))",
          800: "hsl(var(--primary-blue-800))",
          900: "hsl(var(--primary-blue-900))",
        },
        'primary-green': {
          50: "hsl(var(--primary-green-50))",
          100: "hsl(var(--primary-green-100))",
          200: "hsl(var(--primary-green-200))",
          300: "hsl(var(--primary-green-300))",
          400: "hsl(var(--primary-green-400))",
          500: "hsl(var(--primary-green-500))",
          600: "hsl(var(--primary-green-600))",
          700: "hsl(var(--primary-green-700))",
          800: "hsl(var(--primary-green-800))",
          900: "hsl(var(--primary-green-900))",
        },
        'primary-purple': {
          50: "hsl(var(--primary-purple-50))",
          100: "hsl(var(--primary-purple-100))",
          200: "hsl(var(--primary-purple-200))",
          300: "hsl(var(--primary-purple-300))",
          400: "hsl(var(--primary-purple-400))",
          500: "hsl(var(--primary-purple-500))",
          600: "hsl(var(--primary-purple-600))",
          700: "hsl(var(--primary-purple-700))",
          800: "hsl(var(--primary-purple-800))",
          900: "hsl(var(--primary-purple-900))",
        },
        
        // Secondary/Accent Colors
        'accent-orange': {
          50: "hsl(var(--accent-orange-50))",
          100: "hsl(var(--accent-orange-100))",
          200: "hsl(var(--accent-orange-200))",
          300: "hsl(var(--accent-orange-300))",
          400: "hsl(var(--accent-orange-400))",
          500: "hsl(var(--accent-orange-500))",
          600: "hsl(var(--accent-orange-600))",
          700: "hsl(var(--accent-orange-700))",
          800: "hsl(var(--accent-orange-800))",
          900: "hsl(var(--accent-orange-900))",
        },
        'accent-teal': {
          50: "hsl(var(--accent-teal-50))",
          100: "hsl(var(--accent-teal-100))",
          200: "hsl(var(--accent-teal-200))",
          300: "hsl(var(--accent-teal-300))",
          400: "hsl(var(--accent-teal-400))",
          500: "hsl(var(--accent-teal-500))",
          600: "hsl(var(--accent-teal-600))",
          700: "hsl(var(--accent-teal-700))",
          800: "hsl(var(--accent-teal-800))",
          900: "hsl(var(--accent-teal-900))",
        },
        'accent-pink': {
          50: "hsl(var(--accent-pink-50))",
          100: "hsl(var(--accent-pink-100))",
          200: "hsl(var(--accent-pink-200))",
          300: "hsl(var(--accent-pink-300))",
          400: "hsl(var(--accent-pink-400))",
          500: "hsl(var(--accent-pink-500))",
          600: "hsl(var(--accent-pink-600))",
          700: "hsl(var(--accent-pink-700))",
          800: "hsl(var(--accent-pink-800))",
          900: "hsl(var(--accent-pink-900))",
        },
        
        // Semantic Colors
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          50: "hsl(var(--success-50))",
          100: "hsl(var(--success-100))",
          200: "hsl(var(--success-200))",
          300: "hsl(var(--success-300))",
          400: "hsl(var(--success-400))",
          500: "hsl(var(--success-500))",
          600: "hsl(var(--success-600))",
          700: "hsl(var(--success-700))",
          800: "hsl(var(--success-800))",
          900: "hsl(var(--success-900))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          50: "hsl(var(--warning-50))",
          100: "hsl(var(--warning-100))",
          200: "hsl(var(--warning-200))",
          300: "hsl(var(--warning-300))",
          400: "hsl(var(--warning-400))",
          500: "hsl(var(--warning-500))",
          600: "hsl(var(--warning-600))",
          700: "hsl(var(--warning-700))",
          800: "hsl(var(--warning-800))",
          900: "hsl(var(--warning-900))",
        },
        error: {
          50: "hsl(var(--error-50))",
          100: "hsl(var(--error-100))",
          200: "hsl(var(--error-200))",
          300: "hsl(var(--error-300))",
          400: "hsl(var(--error-400))",
          500: "hsl(var(--error-500))",
          600: "hsl(var(--error-600))",
          700: "hsl(var(--error-700))",
          800: "hsl(var(--error-800))",
          900: "hsl(var(--error-900))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
          50: "hsl(var(--info-50))",
          100: "hsl(var(--info-100))",
          200: "hsl(var(--info-200))",
          300: "hsl(var(--info-300))",
          400: "hsl(var(--info-400))",
          500: "hsl(var(--info-500))",
          600: "hsl(var(--info-600))",
          700: "hsl(var(--info-700))",
          800: "hsl(var(--info-800))",
          900: "hsl(var(--info-900))",
        },
        
        // Growth/Investment specific colors
        growth: {
          DEFAULT: "hsl(var(--growth))",
          foreground: "hsl(var(--growth-foreground))",
        },
        
        // Legacy compatibility
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        display: "var(--font-display)",
        body: "var(--font-body)",
        mono: "var(--)",
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        'soft': '0 2px 8px 0 rgba(0, 0, 0, 0.08)',
        'medium': '0 4px 12px 0 rgba(0, 0, 0, 0.12)',
        'strong': '0 8px 24px 0 rgba(0, 0, 0, 0.16)',
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'base': 'var(--shadow-base)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'inner': 'var(--shadow-inner)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, hsl(var(--primary-blue-500)) 0%, hsl(var(--primary-blue-600)) 100%)',
        'gradient-success': 'linear-gradient(135deg, hsl(var(--primary-green-500)) 0%, hsl(var(--primary-green-600)) 100%)',
        'gradient-card': 'linear-gradient(135deg, hsl(var(--card)) 0%, hsl(var(--muted)) 100%)',
        'gradient-accent': 'linear-gradient(135deg, hsl(var(--accent-teal-500)) 0%, hsl(var(--accent-teal-600)) 100%)',
        'gradient-purple': 'linear-gradient(135deg, hsl(var(--primary-purple-500)) 0%, hsl(var(--primary-purple-600)) 100%)',
        'gradient-orange': 'linear-gradient(135deg, hsl(var(--accent-orange-500)) 0%, hsl(var(--accent-orange-600)) 100%)',
        'gradient-pink': 'linear-gradient(135deg, hsl(var(--accent-pink-500)) 0%, hsl(var(--accent-pink-600)) 100%)',
        'gradient-radial': 'radial-gradient(ellipse at center, var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'fade-in': 'fadeIn var(--duration-300) var(--ease-out)',
        'fade-in-up': 'fadeInUp var(--duration-500) var(--ease-out)',
        'fade-in-down': 'fadeInDown var(--duration-500) var(--ease-out)',
        'scale-in': 'scaleIn var(--duration-200) var(--ease-bounce)',
        'slide-in-right': 'slideInRight var(--duration-300) var(--ease-out)',
        'slide-in-left': 'slideInLeft var(--duration-300) var(--ease-out)',
        'shimmer': 'shimmer 2s infinite',
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      transitionDuration: {
        '75': 'var(--duration-75)',
        '100': 'var(--duration-100)',
        '150': 'var(--duration-150)',
        '200': 'var(--duration-200)',
        '300': 'var(--duration-300)',
        '500': 'var(--duration-500)',
        '700': 'var(--duration-700)',
        '1000': 'var(--duration-1000)',
      },
      transitionTimingFunction: {
        'smooth': 'var(--ease-smooth)',
        'bounce': 'var(--ease-bounce)',
      },
    },
  },
  plugins: [],
}