# Prometheus configuration for FinVista Auto-Sync monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FinVista Backend API
  - job_name: 'finvista-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Sync Worker
  - job_name: 'finvista-sync-worker'
    static_configs:
      - targets: ['sync-worker:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # External API Health Checks
  - job_name: 'external-apis'
    static_configs:
      - targets: 
        - 'www.amfiindia.com'
        - 'passbook.epfindia.gov.in'
        - 'yahoo-finance15.p.rapidapi.com'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom sync job metrics
  - job_name: 'sync-jobs'
    static_configs:
      - targets: ['sync-worker:9090']
    metrics_path: '/sync-metrics'
    scrape_interval: 60s